services:
  findelio:
    build: .
    container_name: findelio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      USER_REGISTER_URL_ALLOW_LIST: http://localhost:3000/de-ch/registrierung-bestaetigen
